### ISSUE TITLE
up.sh file doesn't specify a resource group name

### ISSUE THREAD

**Issue by tonyeung** [whiteducksoftware/terraform-scaffold-for-azure#8]
## Is your feature request related to a problem? 
The up.sh file doesn't specify a resource group name and so it errors out.

## Describe the solution you'd like
Provide a place to set the variable if its not already set in the .env

## Describe alternatives you've considered
Manually add it myself

## Additional context
General feedback.

**Comment by nmeisenzahl** [comment]
Hey @tonyeung. Thank you for your feedback. I'll have a look on that one and will keep you posted.

**Comment by tonyeung** [comment]
@nmeisenzahl I've made modifications to the file that allows you to add the values you want if they're not already set in the file. Do you guys accept PRs?

**Comment by nmeisenzahl** [comment]
@tonyeung sure! Feel free to add me as reviewer. Thanks a lot.
